#! /bin/sh
#
# Ensure that NetworkManager includes any additional custom stuff
# when it rewrites /etc/resolv.conf
#
#   Copyright © 2011 Ken Coar
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#================================================================
#
# Drop this file into /etc/NetworkManager/dispatch.d, and put the lines
# you always want to see in your /etc/resolv.conf file into
# /etc/NetworkManager/dispatch.d/resolv.conf.h
#

#
# Do this as a shell function to keep variables local.
# Keep the Environment Clean!
#
function rewrite_resolv_conf() {
    local SYSCONFDIR='/etc/sysconfig'
    local RESOLV_CONF='/etc/resolv.conf'
    local RESOLV_CONF_H='/etc/NetworkManager/dispatcher.d/resolv.conf.h'
    local TMPFILE=/tmp/resolv.conf.$$
    for settings_file in NetworkManager networkmanager nm-settings ; do
        [ -r "$SYSCONFDIR/$settings_file" ] && . $SYSCONFDIR/$settings_file
    done
    [ -r "$RESOLV_CONF_H" ] || return 0

    grep -qFf $RESOLV_CONF_H $RESOLV_CONF && return 0

    cat $RESOLV_CONF_H $RESOLV_CONF > $TMPFILE
    cp $TMPFILE $RESOLV_CONF
    rm -f $TMPFILE
    return 0
}

rewrite_resolv_conf
unset rewrite_resolv_conf
